### PR TITLE
Initial support for MaxScale

### PR DESCRIPTION
**Pull request by mmontes11**
Initial support for MaxScale.

### CODE REVIEW

**Comment by advra** [comment]
Does this still encapsulate discussion with a maxscale failover cluster using VIP previously discussed [here](https://www.reddit.com/r/kubernetes/comments/191qthj/mariadb_ha_metallb_vs_kubevip_static_pod_or/)?

**Comment by mmontes11** [comment]
Hey there @advra ! This PR provides an initial support for provisioning MaxScale instances. In order to address it, a Kubernetes `Service` is provisioned and you can provide extra annotations to it to integrate with third parties like Kube-vip:
- https://kube-vip.io/docs/usage/kubernetes-services/

**Comment by advra** [comment]
Thanks for the clarification. I will be sure to open an issue should I have questions about the service annotations.

**Comment by mmontes11** [comment]
@advra MaxScale support is out. Please take a look at the docs:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/MAXSCALE.md

**Pull request merged**
