### PR TITLE
chore(helm) Adding a PodDisruptionBudget(pdb)

### PR DESCRIPTION
**Pull request by sennerholm**
### Description
Adding a PodDisruptionBudget(pdb) with some testcases for both PDB and Ha

### Checklist
- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by sennerholm** [comment]
Maybe wrong template, i found it deep down in the structure.
I'm unsure about how to update the README.md in the charts directory, I thought a pipeline would do that.

**Review by mmontes11 — CHANGES_REQUESTED** [review]
Hey @sennerholm ! Thanks a lot for the contribution, this is definetly something we need, much appreciated! 🙏🏻 

Changes LGTM! Could please fix the linting errors? They are just cosmetic changes
- https://github.com/mariadb-operator/mariadb-operator/actions/runs/11133673637/job/30960208539?pr=899
- https://github.com/mariadb-operator/mariadb-operator/actions/runs/11133673624/job/30960195190?pr=899

Also, would you mind reverting the changes in the README.md? I appreciate your good will for getting everything documented but I would try to avoid having non released changes in the `main` branch, so people doesn't get confused. This is something already generated by our release process, don't worry about it.

**Comment by sennerholm** [comment]
Hi @mmontes11 

I have reverted the README.md updates and trying to fix the lint problems. Could you retrigger the Workflows so we can check if it fixed the linting errors? I have tried to verify on my side, but didn't have all tools installed localy.

Sincerely
Mikael

> Hey @sennerholm ! Thanks a lot for the contribution, this is definetly something we need, much appreciated! 🙏🏻
> 
> Changes LGTM! Could please fix the linting errors? They are just cosmetic changes:

**Review by mmontes11 — APPROVED** [review]
LGTM! 👍🏻 

Thanks a lot for this contribution @sennerholm ! Very much appreciated! 🙇🏻 

This will certainly facilitate the road to production for our users! 🚀

**Pull request merged**
