### PR TITLE
feat(ipv6Cluster): add ipv6Cluster value for galera (bool) 

### PR DESCRIPTION
**Pull request by valentin2105**
Hi,

So, here a PR to implement the Galera's value `ipv6Cluster`  (bool) in the Galera spec, in the CRD, to pass this value to the init container to modify the galera configuration if ipv6 is enabled. 

I'm pretty new in CRD and Go Object development, so please if I can improve something, let me know. 

And it seem difficult to test that, on my side (with new crd and go links between two repos).

If you have any idea how I can test that ? 

Thanks !

### CODE REVIEW

**Comment by mmontes11** [comment]
Hey thanks for the PR!

It would be great if we could test all the IPv6 changes together before merging. For doing so, you can:
- Setup a development environment following this [guide](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DEVELOPMENT.md)
- In `init`:
    - Bump the init image [here](https://github.com/mariadb-operator/init/blob/main/make/deploy.mk#L6)
    - `make docker-build`: This will build the `init` docker image locally
    - `make docker-load`: This will load the `init` image in your KIND cluster
- In `mariadb-operator` repository:
    - `make gen`:  to generate the new CRDs. Make sure you commit the changes so the CI can pass.
    - `make install`: Install the new CRDs on the cluster.
    - Refer to the previous dev guide to know how to [run](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DEVELOPMENT.md#run) locally and [test](https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DEVELOPMENT.md#test)
    - When you apply an example, make sure to bump the init image [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_mariadb_galera.yaml#L52)
    
This will enable you to test IPv6 changes locally. Once you are done, I will release a new version of `init` so you can refer to it in the [defaults](https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/mariadb_galera_types.go#L234) and raise another PR in `mariadb-operator`

**Comment by valentin2105** [comment]
Hey,

I made some tests, 

```
=== RUN   TestAPIs
Running Suite: Webhook Suite
============================
Random Seed: 1692746921
Will run 16 of 16 specs

••••••••••••••••

Ran 16 of 16 Specs in 7.291 seconds
SUCCESS! -- 16 Passed | 0 Failed | 0 Pending | 0 Skipped
```

```

--- FAIL: TestAPIs (183.21s)
FAIL
coverage: 46.8% of statements
FAIL    github.com/mariadb-operator/mariadb-operator/controllers        183.224s
=== RUN   TestRecoveryStatusGetSet
--- PASS: TestRecoveryStatusGetSet (0.00s)
=== RUN   TestRecoveryStatusBootstrap
--- PASS: TestRecoveryStatusBootstrap (3.00s)
=== RUN   TestRecoveryStatusSafeToBootstrap
=== RUN   TestRecoveryStatusSafeToBootstrap/no_status
=== RUN   TestRecoveryStatusSafeToBootstrap/no_pods
=== RUN   TestRecoveryStatusSafeToBootstrap/negative_seqno
=== RUN   TestRecoveryStatusSafeToBootstrap/no_source
=== RUN   TestRecoveryStatusSafeToBootstrap/safe_to_bootstrap_source
--- PASS: TestRecoveryStatusSafeToBootstrap (0.00s)
    --- PASS: TestRecoveryStatusSafeToBootstrap/no_status (0.00s)
    --- PASS: TestRecoveryStatusSafeToBootstrap/no_pods (0.00s)
    --- PASS: TestRecoveryStatusSafeToBootstrap/negative_seqno (0.00s)
    --- PASS: TestRecoveryStatusSafeToBootstrap/no_source (0.00s)
    --- PASS: TestRecoveryStatusSafeToBootstrap/safe_to_bootstrap_source (0.00s)
=== RUN   TestRecoveryStatusIsComplete
=== RUN   TestRecoveryStatusIsComplete/no_status
=== RUN   TestRecoveryStatusIsComplete/no_pods
=== RUN   TestRecoveryStatusIsComplete/partial_state
=== RUN   TestRecoveryStatusIsComplete/full_state
=== RUN   TestRecoveryStatusIsComplete/partially_recovered
=== RUN   TestRecoveryStatusIsComplete/fully_recovered
=== RUN   TestRecoveryStatusIsComplete/incomplete
=== RUN   TestRecoveryStatusIsComplete/incomplete_seqnos
=== RUN   TestRecoveryStatusIsComplete/complete
=== RUN   TestRecoveryStatusIsComplete/complete_with_intersection
=== RUN   TestRecoveryStatusIsComplete/fully_complete
--- PASS: TestRecoveryStatusIsComplete (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/no_status (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/no_pods (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/partial_state (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/full_state (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/partially_recovered (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/fully_recovered (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/incomplete (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/incomplete_seqnos (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/complete (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/complete_with_intersection (0.00s)
    --- PASS: TestRecoveryStatusIsComplete/fully_complete (0.00s)
=== RUN   TestRecoveryStatusBootstrapSource
=== RUN   TestRecoveryStatusBootstrapSource/no_status
=== RUN   TestRecoveryStatusBootstrapSource/missing_pods
=== RUN   TestRecoveryStatusBootstrapSource/safe_to_bootstrap
=== RUN   TestRecoveryStatusBootstrapSource/incomplete_recovery
=== RUN   TestRecoveryStatusBootstrapSource/partially_recovered
=== RUN   TestRecoveryStatusBootstrapSource/partially_recovered_with_different_seqnos
=== RUN   TestRecoveryStatusBootstrapSource/partially_recovered_with_different_seqnos_and_safe_to_bootstrap
=== RUN   TestRecoveryStatusBootstrapSource/fully_recovered
=== RUN   TestRecoveryStatusBootstrapSource/fully_recovered_with_different_seqnos
=== RUN   TestRecoveryStatusBootstrapSource/fully_recovered_with_different_seqnos_and_safe_to_bootstrap
--- PASS: TestRecoveryStatusBootstrapSource (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/no_status (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/missing_pods (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/safe_to_bootstrap (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/incomplete_recovery (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/partially_recovered (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/partially_recovered_with_different_seqnos (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/partially_recovered_with_different_seqnos_and_safe_to_bootstrap (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/fully_recovered (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/fully_recovered_with_different_seqnos (0.00s)
    --- PASS: TestRecoveryStatusBootstrapSource/fully_recovered_with_different_seqnos_and_safe_to_bootstrap (0.00s)
PASS
coverage: 20.3% of statements
ok      github.com/mariadb-operator/mariadb-operator/pkg/controller/galera      3.019s  coverage: 20.3% of statements
=== RUN   TestInmutableWebhook
=== RUN   TestInmutableWebhook/update_mutable_field
=== RUN   TestInmutableWebhook/update_inmutable_field
=== RUN   TestInmutableWebhook/update_inmutableinit_field
=== RUN   TestInmutableWebhook/init_inmutableinit_field
=== RUN   TestInmutableWebhook/restore_init
=== RUN   TestInmutableWebhook/complex_update
--- PASS: TestInmutableWebhook (0.00s)
    --- PASS: TestInmutableWebhook/update_mutable_field (0.00s)
    --- PASS: TestInmutableWebhook/update_inmutable_field (0.00s)
    --- PASS: TestInmutableWebhook/update_inmutableinit_field (0.00s)
    --- PASS: TestInmutableWebhook/init_inmutableinit_field (0.00s)
    --- PASS: TestInmutableWebhook/restore_init (0.00s)
    --- PASS: TestInmutableWebhook/complex_update (0.00s)
PASS
coverage: 94.1% of statements
ok      github.com/mariadb-operator/mariadb-operator/pkg/webhook        0.033s  coverage: 94.1% of statements
FAIL
make: *** [make/dev.mk:23: test] Error 1

```
```
❯ sudo kubectl get po
NAME               READY   STATUS                  RESTARTS        AGE
mariadb-galera-0   0/2     Init:ErrImagePull       0               85s
mariadb-galera-1   0/2     Init:ImagePullBackOff   0               73m
mariadb-galera-2   0/2     Init:ImagePullBackOff   0               73m
mariadb-repl-0     1/1     Running                 0               67m
mariadb-repl-1     1/1     Running                 1 (8m17s ago)   67m
mariadb-repl-2     1/1     Running                 0               67m

 Failed to pull image "ghcr.io/mariadb-operator/init:v0.0.5": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/mariadb-operator/init:v0.0.5": failed to resolve reference "ghcr.io/mariadb-operator/init:v0.0.5": failed to do request: Head "https://ghcr.io/v2/mariadb-operator/init/manifests/v0.0.5": net/http: TLS handshake timeout
```

I got some issue on the mariadb-galera side. I don't know why. The Kind is pretty obscure, I can't ping my pods or reach services. 

My CRD field seem be working `ipv6Cluster` : 

```
❯ sudo kubectl get mariadb mariadb-galera -o yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  creationTimestamp: "2023-08-22T23:32:34Z"
  generation: 3
  name: mariadb-galera
  namespace: default
  resourceVersion: "49462"
  uid: 1b670aa2-6b86-46c6-9d2d-646db1b68d26
spec:
  connection:
    secretName: conn-mdb-galera
    secretTemplate:
      key: dsn
  database: test
  galera:
    enabled: true
    ipv6Cluster: false
    recovery:
      clusterBootstrapTimeout: 5m0s
```

I'm a bit stuck to find what I need to do.

**Comment by valentin2105** [comment]
Hi @mmontes11 , 

It's probably nothing but I'm not able to build init, 

```
------
 > [builder 4/6] RUN go mod download:
12.20 go: github.com/valentin2105/mariadb-operator@v0.0.1: parsing go.mod:
12.20   module declares its path as: github.com/mariadb-operator/mariadb-operator
12.20           but was required as: github.com/valentin2105/mariadb-operator
------
```

I had to create a tag on my repo to point to it in `go.mod` because the `@feat/ipv6Cluster ` didn't worked. 
And If I change the `mariadb-operator` module with my github name, (I don't know how) it will update that on this current PR. 

So I'm a bit stuck.  Sorry about that

**Comment by mmontes11** [comment]
Hey there @valentin2105 ! 

I think you are facing this problem because you are working in a fork, something that I haven't tested TBH. This seems to be a recurrent problem:
- https://stackoverflow.com/questions/61311436/how-to-fix-parsing-go-mod-module-declares-its-path-as-x-but-was-required-as-y

Let me know if this helps so we can create a procedure to develop `init` and `agent` images to be tested locally by future contributors. Sorry for the inconvenience 🙏🏻

**Pull request closed without merging**
