### PR TITLE
Support history limits in `Backup` and `SqlJob` resources

### PR DESCRIPTION
**Pull request by mbezhanov**
As requested in #641, this PR enables the `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` fields for scheduled `Backup` and `SqlJob` resources.

Is the test coverage sufficient or should I add some more tests?

Close https://github.com/mariadb-operator/mariadb-operator/issues/641

### CODE REVIEW

**Comment by mbezhanov** [comment]
I wasn't too happy with my original test coverage, so I added some additional test cases to `backup_controller_test.go` and `sqljob_controller_test.go`.  If it's too much, let me know, and I'll revert and/or change them accordingly.

**Review by mmontes11 — APPROVED** [review]
LGTM! 🚀 

It's great to see how you easily manage to understand the code. Thanks a lot for your contribution and specially for taking care and extending the `Backup` / `SqlJob` tests! ⭐ 

I have a minor comment: it might be worth considering adding a `CronJobTemplate` type to centralize all the `CronJob`-related fields and avoid duplicating them in `Backup` and `SqlJob`, embedding the `CronJobTemplate` on them instead.. Saying this because we have plans to support other `CronJob` fields like [timeZone](https://github.com/mariadb-operator/mariadb-operator/issues/383) at some point.

What are your thoughts about this? For now I think it is fine as it is, but we can open an issue if you think it would be useful.

**Comment by mbezhanov** [comment]
Ah yes, that makes total sense. I can certainly open another PR where I introduce a `CronJobTemplate`. In fact, I may prepare this as a PR implementing #383.

> It's great to see how easily you manage to understand the code. Thanks a lot for your contribution and specially for taking care and extending the `Backup` / `SqlJob` tests! ⭐

Happy to help! Thanks for your kind words!

**Comment by mmontes11** [comment]
> Have you considered anything in that direction that I should take into account, and do you accept such PRs in general?

PRs welcome! tests should be first class citizens and they can always be improved!

**Pull request merged**
